const path = '/src/svg/external/';

export const techIcons = {
    html: `${path}Icon-Html.svg`,
    css: `${path}Icon-Css.svg`,
    js: `${path}Icon-Js.svg`,
    php: `${path}Icon-Php.svg`,
    nodejs: `${path}Icon-NodeJs.svg`,
    ex: `${path}Icon-Express.svg`,
    ejs: `${path}Icon-Ejs.svg`,
    djs: `${path}Icon-Discordjs.svg`,
    joo: `${path}Icon-Joomla.svg`,
    wp: `${path}Icon-Wordpress.svg`,
    xd: `${path}Icon-Xd.svg`,
    ps: `${path}Icon-Ps.svg`,
    figma: `${path}Icon-Figma.svg`,
    linux: `${path}Icon-Linux.svg`,
    bash: `${path}Icon-Bash.svg`,
    cloudflare: `${path}Icon-Cloudflare.svg`,
    aws: `${path}Icon-Aws.svg`,
    mysql: `${path}Icon-Mysql.svg`,
    mongodb: `${path}Icon-Mongodb.svg`,
    eu: `${path}Icon-Eu.svg`,
    ch: `${path}Icon-Ch.svg`,
    java: `${path}Icon-Java.svg`,
    maven: `${path}Icon-Maven.svg`,
    cs: `${path}Icon-Cs.svg`,
    dotnet: `${path}Icon-Dotnet.svg`,
    notion: `${path}Icon-Notion.svg`
};

export const techNames = {
    html: 'HTML',
    css: 'CSS',
    js: 'JavaScript',
    php: 'Php',
    nodejs: 'NodeJs',
    ex: 'ExpressJs',
    ejs: 'EJS',
    djs: 'DiscordJs',
    joo: 'Joomla',
    wp: 'WordPress',
    xd: 'Adobe XD',
    ps: 'Adobe Photoshop',
    figma: 'Figma',
    linux: 'Linux',
    bash: 'Bash',
    cloudflare: 'Cloudflare',
    aws: 'Amazon Web Services',
    mysql: 'MySQL',
    mongodb: 'MongoDB',
    eu: 'DSGVO, Datenschutzgrundverordnung',
    ch: 'DSG, Datenschutzgesetz',
    java: 'Java',
    maven: 'Maven',
    cs: 'CSharp',
    dotnet: 'DotNet',
    notion: 'Notion'
}